"""empty message

Revision ID: 12bbf7f971b3
Revises: 5823e4224d02
Create Date: 2022-09-10 19:26:33.965202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bbf7f971b3'
down_revision = '5823e4224d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_pertanian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sayuran_id', sa.Integer(), nullable=True),
    sa.Column('provinsi_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provinsi_id'], ['Provinsi.id'], ),
    sa.ForeignKeyConstraint(['sayuran_id'], ['Sayuran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil_pertanian')
    # ### end Alembic commands ###
