"""empty message

Revision ID: 1e60df51a36d
Revises: 7f33a9b72166
Create Date: 2022-08-27 13:52:25.780245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e60df51a36d'
down_revision = '7f33a9b72166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
